name: "🐞 Bug"
description: "버그를 신고해주세요"
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: 🐛 버그 설명
      description: 어떤 문제가 발생했는지 설명해주세요.
      placeholder: 명확하고 구체적으로 적어주세요!
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🧪 재현 절차
      description: 버그를 재현할 수 있는 단계들을 순서대로 작성해주세요.
      placeholder: 예) 1. 로그인 → 2. 버튼 클릭 → 3. 오류 발생
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🎯 기대 동작
      description: 원래 어떻게 동작했어야 하는지 설명해주세요.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 📸 스크린샷 / 콘솔 로그
      description: 관련된 이미지, 에러 메시지, 콘솔 로그가 있다면 첨부해주세요.
  - type: input
    attributes:
      label: 💻 환경 정보
      description: 사용한 운영체제, 브라우저, 버전 등
      placeholder: 예) Windows 11 / Chrome 123
