spring:
  config:
    activate:
      on-profile: dev
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: System1234
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: none
file:
  upload:
    all:
      path: ./files
