spring:
  config:
    activate:
      on-profile: dev
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test;MODE=POSTGRESQL
    username: root
    password:
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: create
file:
  upload:
    all:
      path: ./files
